### ISSUE TITLE
Classic mode

### ISSUE THREAD

**Issue by danimesq** [lbarman/clearwater#1]
Classic mode when people can post each individual notes, like other notes apps.

**Comment by lbarman** [comment]
A multi-user feature ?
It would be interesting. The drawback is that they all need to know the (symmetric) password with the current implementation.

**Comment by danimesq** [comment]
Not multi-user feature. A classic mode to work like other notes apps, like Google Keep, Samsung Notes, etc.

**Comment by lbarman** [comment]
Sorry, I checked Google Keep, and your request is still not clear.

**Comment by danimesq** [comment]
![classic](https://cloud.githubusercontent.com/assets/6765277/12919217/3bfbf330-cf2a-11e5-8f56-20054b85dc73.png)

**Comment by lbarman** [comment]
add to css/custom.css :
.col-md-2 h2 { display:none; }
.add { border-top: 0px; padding-top: 0px; }

**Comment by danimesq** [comment]
Will be better have an separate own mode for it.

**Comment by lbarman** [comment]
Don't hesitate to change and do a pull request, all improvements are welcome.

**Comment by danimesq** [comment]
Whats the need to close an issue if calling for an PR?

**Comment by lbarman** [comment]
Just not to keep the issue open (since you seem to wish to do it). Does it changes anything related to the future PR? I can reopen and assign you

**Comment by danimesq** [comment]
Yes, Its an open question, then the issue need remain open. Ok, you can open and assign me. I'm inserting this app in [Modern OS](https://github.com/DaniellMesquita/Modern-OS) and I need improve it.

**Comment by lbarman** [comment]
Great!

**Comment by danimesq** [comment]
This isn't a conventional notes app, but an tasks app.
